/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 28 02:51:52 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.ATMCard;
import tutorial.BankAccount;
import tutorial.Company;
import tutorial.CurrentAccount;
import tutorial.Owner;
import tutorial.Person;
import tutorial.SavingsAccount;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ATMCard_ESTest extends ATMCard_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Company company0 = new Company("-(");
      int[] intArray0 = new int[2];
      ATMCard aTMCard0 = new ATMCard(company0, (BankAccount) null, intArray0);
      assertTrue(aTMCard0.isEnabled());
      
      aTMCard0.invalidate();
      boolean boolean0 = aTMCard0.isEnabled();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CurrentAccount currentAccount0 = new CurrentAccount((Owner) null, 0);
      ATMCard aTMCard0 = new ATMCard((Owner) null, currentAccount0, (int[]) null);
      aTMCard0.getPin();
      assertTrue(aTMCard0.isEnabled());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Person person0 = new Person(">kl*#7^C", "[fj2kjA1'");
      int[] intArray0 = new int[0];
      ATMCard aTMCard0 = new ATMCard(person0, (BankAccount) null, intArray0);
      aTMCard0.getPin();
      assertTrue(aTMCard0.isEnabled());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CurrentAccount currentAccount0 = new CurrentAccount((Owner) null, 1);
      int[] intArray0 = new int[4];
      ATMCard aTMCard0 = new ATMCard((Owner) null, currentAccount0, intArray0);
      aTMCard0.getOwner();
      assertTrue(aTMCard0.isEnabled());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Company company0 = new Company("-(");
      int[] intArray0 = new int[2];
      ATMCard aTMCard0 = new ATMCard(company0, (BankAccount) null, intArray0);
      aTMCard0.getAccount();
      assertTrue(aTMCard0.isEnabled());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Company company0 = new Company("");
      CurrentAccount currentAccount0 = new CurrentAccount(company0, (-857));
      int[] intArray0 = new int[3];
      currentAccount0.balance = 98;
      ATMCard aTMCard0 = new ATMCard(company0, currentAccount0, intArray0);
      aTMCard0.getAccount();
      assertTrue(aTMCard0.isEnabled());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Person person0 = new Person("ctau1G:t^:$Xer$r", "");
      SavingsAccount savingsAccount0 = new SavingsAccount(person0);
      savingsAccount0.balance = (-4715);
      ATMCard aTMCard0 = new ATMCard(person0, savingsAccount0, (int[]) null);
      aTMCard0.getAccount();
      assertTrue(aTMCard0.isEnabled());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Person person0 = new Person((String) null, "tutorial.Company");
      CurrentAccount currentAccount0 = new CurrentAccount(person0, 550);
      int[] intArray0 = new int[5];
      ATMCard aTMCard0 = new ATMCard(person0, currentAccount0, intArray0);
      aTMCard0.getOwner();
      assertTrue(aTMCard0.isEnabled());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Person person0 = new Person((String) null, "tutorial.Company");
      CurrentAccount currentAccount0 = new CurrentAccount(person0, 550);
      int[] intArray0 = new int[5];
      ATMCard aTMCard0 = new ATMCard(person0, currentAccount0, intArray0);
      aTMCard0.getPin();
      assertTrue(aTMCard0.isEnabled());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Person person0 = new Person((String) null, "tutorial.Company");
      CurrentAccount currentAccount0 = new CurrentAccount(person0, 550);
      int[] intArray0 = new int[5];
      ATMCard aTMCard0 = new ATMCard(person0, currentAccount0, intArray0);
      aTMCard0.setAccount(currentAccount0);
      assertTrue(aTMCard0.isEnabled());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Person person0 = new Person((String) null, "tutorial.Company");
      CurrentAccount currentAccount0 = new CurrentAccount(person0, 550);
      int[] intArray0 = new int[5];
      ATMCard aTMCard0 = new ATMCard(person0, currentAccount0, intArray0);
      boolean boolean0 = aTMCard0.isEnabled();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Person person0 = new Person((String) null, "tutorial.Company");
      CurrentAccount currentAccount0 = new CurrentAccount(person0, 550);
      int[] intArray0 = new int[5];
      ATMCard aTMCard0 = new ATMCard(person0, currentAccount0, intArray0);
      aTMCard0.setPin(intArray0);
      assertTrue(aTMCard0.isEnabled());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Person person0 = new Person((String) null, "tutorial.Company");
      CurrentAccount currentAccount0 = new CurrentAccount(person0, 550);
      int[] intArray0 = new int[5];
      ATMCard aTMCard0 = new ATMCard(person0, currentAccount0, intArray0);
      aTMCard0.setOwner(person0);
      assertTrue(aTMCard0.isEnabled());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Person person0 = new Person((String) null, "tutorial.Company");
      CurrentAccount currentAccount0 = new CurrentAccount(person0, 550);
      int[] intArray0 = new int[5];
      ATMCard aTMCard0 = new ATMCard(person0, currentAccount0, intArray0);
      aTMCard0.getAccount();
      assertTrue(aTMCard0.isEnabled());
  }
}
