/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 28 02:53:00 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.collections.list.UnmodifiableList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Bank;
import tutorial.Company;
import tutorial.CurrentAccount;
import tutorial.Person;
import tutorial.SavingsAccount;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Bank_ESTest extends Bank_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Bank bank0 = new Bank();
      Person person0 = new Person("F", "F");
      SavingsAccount savingsAccount0 = new SavingsAccount(person0);
      bank0.addAccount(savingsAccount0);
      boolean boolean0 = bank0.hasBankAccount(savingsAccount0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Bank bank0 = new Bank();
      Company company0 = new Company("|Z");
      CurrentAccount currentAccount0 = new CurrentAccount(company0, 1);
      boolean boolean0 = bank0.hasBankAccount(currentAccount0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Bank bank0 = new Bank();
      // Undeclared exception!
      try { 
        bank0.addAccounts((UnmodifiableList) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractCollection", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Bank bank0 = new Bank();
      Company company0 = new Company("|Z");
      CurrentAccount currentAccount0 = new CurrentAccount(company0, 1);
      bank0.removeAccount(currentAccount0);
      assertEquals(0, currentAccount0.getBalance());
  }
}
