/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 28 02:56:47 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Company;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Company_ESTest extends Company_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Company company0 = new Company((String) null);
      String string0 = company0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Company company0 = new Company("im$J");
      String string0 = company0.getName();
      assertEquals("im$J", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Company company0 = new Company("");
      String string0 = company0.getName();
      assertEquals("", string0);
  }
}
