/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 28 02:56:40 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Owner;
import tutorial.SavingsAccount;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SavingsAccount_ESTest extends SavingsAccount_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount((Owner) null);
      savingsAccount0.balance = (-2213);
      boolean boolean0 = savingsAccount0.withdraw((-2213));
      assertEquals(0, savingsAccount0.getBalance());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount((Owner) null);
      savingsAccount0.balance = (-2213);
      savingsAccount0.deposit((-138));
      boolean boolean0 = savingsAccount0.withdraw((-2213));
      assertEquals((-2351), savingsAccount0.getBalance());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount((Owner) null);
      boolean boolean0 = savingsAccount0.withdraw((-2213));
      assertEquals(2213, savingsAccount0.getBalance());
      assertTrue(boolean0);
  }
}
